apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
  name: sample-gha
spec:
  replicas: 3
  selector:
    matchLabels:
      name: sample-gha
  template:
    metadata:
      labels:
        name: sample-gha
    spec:
      containers:
      - name: sample-gha
        image: banzaicode/sample-githubactions
        ports:
        - containerPort: 80
          name: http